# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alex Webber
email: "webber512@live.missouristate.edu"
description: >- # this means to ignore newlines until "baseurl:"
  Student | Developer
#baseurl: "" # the subpath of your site, e.g. /blog
url: "webber512.github.io" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  jekyll

repository: "webber512/webber512.github.io"

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap

# A list of the pages to display in the navigation bar
header_pages:
  - portfolio
  - about
  - blog

collections:
  projects:
    output: true
    permalink: /projects/:path/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

theme: jekyll-theme-cayman